backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**/*'

frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**/*'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - 'README.md'
          - 'CONTRIBUTING.md'
          - 'SECURITY.md'

github:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
