#!/usr/bin/env bash
# Smoke test for S76: Document summary fast-path using section summaries.
# (1) Ingest a fixture document (section summaries are generated by S75 node).
# (2) Poll until stage=complete.
# (3) POST /summarize/{id} with mode=executive and force_refresh=true.
#     Assert HTTP 200 and streaming response contains non-empty content.
# (4) GET /summarize/{id}/cached, assert 'executive' key is present.
# Requires the backend to be running on localhost:7820.

set -euo pipefail

BASE="http://localhost:7820"
FIXTURE="backend/tests/fixtures/art_of_unix_ch1.txt"

if [ ! -f "$FIXTURE" ]; then
  echo "FAIL: fixture not found at $FIXTURE"
  exit 1
fi

# POST /ingest
echo "Ingesting fixture..."
INGEST_RESP=$(curl -s -X POST "${BASE}/ingest" \
  -F "file=@${FIXTURE};type=text/plain" \
  -F "content_type=notes")

DOC_ID=$(echo "$INGEST_RESP" | python3 -c "import sys, json; print(json.load(sys.stdin)['document_id'])" 2>/dev/null || echo "")

if [ -z "$DOC_ID" ]; then
  echo "FAIL: could not parse document_id from ingest response: $INGEST_RESP"
  exit 1
fi
echo "Document ID: $DOC_ID"

# Poll GET /documents/{id} until stage=complete or timeout
MAX_WAIT=180
ELAPSED=0
STAGE=""
while [ "$STAGE" != "complete" ] && [ "$ELAPSED" -lt "$MAX_WAIT" ]; do
  sleep 5
  ELAPSED=$((ELAPSED + 5))
  STAGE=$(curl -s "${BASE}/documents/${DOC_ID}" | python3 -c "import sys, json; print(json.load(sys.stdin).get('stage', ''))" 2>/dev/null || echo "")
  echo "  stage=${STAGE} (${ELAPSED}s)"
done

if [ "$STAGE" != "complete" ]; then
  echo "FAIL: document did not reach stage=complete within ${MAX_WAIT}s (last stage: ${STAGE})"
  exit 1
fi

# POST /summarize/{id} with mode=executive and force_refresh=true
# The streaming response is SSE; collect all data lines and check for non-empty token content.
echo "Requesting executive summary (force_refresh=true)..."
HTTP_CODE=$(curl -s -o /tmp/s76_summary.txt -w "%{http_code}" \
  -X POST "${BASE}/summarize/${DOC_ID}" \
  -H "Content-Type: application/json" \
  -d '{"mode": "executive", "force_refresh": true}')

if [ "$HTTP_CODE" != "200" ]; then
  echo "FAIL: POST /summarize/${DOC_ID} returned ${HTTP_CODE} (expected 200)"
  cat /tmp/s76_summary.txt
  exit 1
fi

# Check that the response contains at least one non-empty token event
HAS_CONTENT=$(python3 -c "
import json, sys
content = open('/tmp/s76_summary.txt').read()
lines = [l for l in content.split('\n') if l.startswith('data: ')]
tokens = []
for line in lines:
    try:
        obj = json.loads(line[6:])
        if 'token' in obj and obj['token']:
            tokens.append(obj['token'])
    except Exception:
        pass
print('yes' if tokens else 'no')
" 2>/dev/null || echo "no")

if [ "$HAS_CONTENT" != "yes" ]; then
  echo "FAIL: streaming response contains no non-empty token events"
  cat /tmp/s76_summary.txt
  exit 1
fi
echo "PASS: POST /summarize/${DOC_ID} returned HTTP 200 with non-empty content"

# GET /summarize/{id}/cached — assert 'executive' key is present
HTTP_CODE=$(curl -s -o /tmp/s76_cached.json -w "%{http_code}" \
  "${BASE}/summarize/${DOC_ID}/cached")

if [ "$HTTP_CODE" != "200" ]; then
  echo "FAIL: GET /summarize/${DOC_ID}/cached returned ${HTTP_CODE} (expected 200)"
  exit 1
fi

HAS_EXECUTIVE=$(python3 -c "
import json
data = json.load(open('/tmp/s76_cached.json'))
print('yes' if 'executive' in data else 'no')
" 2>/dev/null || echo "no")

if [ "$HAS_EXECUTIVE" != "yes" ]; then
  echo "FAIL: GET /summarize/${DOC_ID}/cached does not contain 'executive' key"
  cat /tmp/s76_cached.json
  exit 1
fi

echo "PASS: GET /summarize/${DOC_ID}/cached contains 'executive' key"
echo "PASS: S76 smoke test complete"
exit 0
