"""graph concept edges in sqlite

Revision ID: b6d91c364d48
Revises: f1a2b3c4d5e6
Create Date: 2026-10-01 12:50:46.294694

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b6d91c364d48'
down_revision: str | Sequence[str] | None = 'f1a2b3c4d5e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _has_table(table: str) -> bool:
    return table in sa.inspect(op.get_bind()).get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    # db_init's legacy bridge builds pre-Alembic databases from the live models before
    # stamping the baseline, so on that path these tables already exist (see cae3aba739eb).
    if not _has_table('graph_import_state'):
        _create_import_state()
    if not _has_table('graph_concept_documents'):
        _create_concept_documents()
    if not _has_table('graph_concept_edges'):
        _create_concept_edges()


def _create_import_state() -> None:
    op.create_table('graph_import_state',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('imported_json', sqlite.JSON(), nullable=False),
    sa.Column('skipped_json', sqlite.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )


def _create_concept_documents() -> None:
    op.create_table('graph_concept_documents',
    sa.Column('concept_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'document_id')
    )
    with op.batch_alter_table('graph_concept_documents', schema=None) as batch_op:
        batch_op.create_index('ix_graph_concept_documents_document', ['document_id'], unique=False)


def _create_concept_edges() -> None:
    op.create_table('graph_concept_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('library_id', sa.String(), nullable=True),
    sa.CheckConstraint("kind IN ('related', 'prerequisite')", name='ck_graph_concept_edge_kind'),
    sa.ForeignKeyConstraint(['source_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'source_id', 'target_id', name='uq_graph_concept_edge')
    )
    with op.batch_alter_table('graph_concept_edges', schema=None) as batch_op:
        batch_op.create_index('ix_graph_concept_edges_target', ['kind', 'target_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_concept_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_concept_edges_target')

    op.drop_table('graph_concept_edges')
    with op.batch_alter_table('graph_concept_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_concept_documents_document')

    op.drop_table('graph_concept_documents')
    op.drop_table('graph_import_state')
    # ### end Alembic commands ###
