"""baseline

The schema as of the Alembic cutover. Databases predating this revision are brought
up to it by db_init.create_all_tables() (the legacy bridge) and then stamped, so this
revision only ever executes against a fresh database.

Revision ID: 938e28777f4a
Revises:
Create Date: 2026-07-15 18:24:41.693483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from app.db_init import ALL_FTS5_DDL

# revision identifiers, used by Alembic.
revision: str = '938e28777f4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_FTS_TABLES = (
    "chunks_fts",
    "notes_fts",
    "images_fts",
    "flashcards_fts",
    "chat_messages_fts",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_target', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_document_id'), ['document_id'], unique=False)

    op.create_table('canonical_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('parent_tag', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('document_ids', sqlite.JSON(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('title_auto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_last_message_at'), ['last_message_at'], unique=False)

    op.create_table('chat_suggestion_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('bloom_level', sa.Integer(), nullable=False),
    sa.Column('was_asked', sa.Boolean(), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_suggestion_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_suggestion_history_document_id'), ['document_id'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('pdf_page_number', sa.Integer(), nullable=True),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('code_language', sa.String(length=50), nullable=True),
    sa.Column('code_signature', sa.Text(), nullable=True),
    sa.Column('entities_text', sa.Text(), nullable=True),
    sa.Column('context_header', sa.Text(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('section_heading', sa.String(length=300), nullable=True),
    sa.Column('pdf_page_number', sa.Integer(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_document_id'), ['document_id'], unique=False)

    op.create_table('cluster_suggestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('suggested_name', sa.String(), nullable=False),
    sa.Column('note_ids', sqlite.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_snippets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_snippets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_snippets_document_id'), ['document_id'], unique=False)

    op.create_table('collection_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('member_type', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'collection_id', 'member_type', name='uq_collection_member')
    )
    with op.batch_alter_table('collection_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_members_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_members_member_id'), ['member_id'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('parent_collection_id', sa.String(), nullable=True),
    sa.Column('auto_document_id', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index('idx_collections_auto_doc_id', ['auto_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_auto_document_id'), ['auto_document_id'], unique=False)

    op.create_table('concepts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('evidence_json', sqlite.JSON(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('salience', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index('idx_concepts_parent_id', ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_concepts_status'), ['status'], unique=False)

    op.create_table('content_activity',
    sa.Column('member_type', sa.String(length=16), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('last_meaningful_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('member_type', 'member_id')
    )
    with op.batch_alter_table('content_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_activity_last_meaningful_at'), ['last_meaningful_at'], unique=False)

    op.create_table('document_tag_index',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('tag_full', sa.String(), nullable=False),
    sa.Column('tag_root', sa.String(), nullable=False),
    sa.Column('tag_parent', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('document_id', 'tag_full')
    )
    with op.batch_alter_table('document_tag_index', schema=None) as batch_op:
        batch_op.create_index('idx_document_tag_index_document_id', ['document_id'], unique=False)
        batch_op.create_index('idx_document_tag_index_tag_full', ['tag_full'], unique=False)

    op.create_table('document_tag_provenance',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('tag_full', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tagger_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('document_id', 'tag_full')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('conversation_metadata', sqlite.JSON(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('video_title', sa.String(), nullable=True),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)

    op.create_table('enrichment_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_document_id'), ['document_id'], unique=False)

    op.create_table('eval_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('hit_rate_5', sa.Float(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('answer_relevance', sa.Float(), nullable=True),
    sa.Column('context_precision', sa.Float(), nullable=True),
    sa.Column('context_recall', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('eval_kind', sa.String(), nullable=True),
    sa.Column('citation_support_rate', sa.Float(), nullable=True),
    sa.Column('theme_coverage', sa.Float(), nullable=True),
    sa.Column('no_hallucination', sa.Float(), nullable=True),
    sa.Column('conciseness_pct', sa.Float(), nullable=True),
    sa.Column('factuality', sa.Float(), nullable=True),
    sa.Column('atomicity', sa.Float(), nullable=True),
    sa.Column('clarity_avg', sa.Float(), nullable=True),
    sa.Column('routing_accuracy', sa.Float(), nullable=True),
    sa.Column('per_route', sqlite.JSON(), nullable=True),
    sa.Column('ablation_metrics', sqlite.JSON(), nullable=True),
    sa.Column('extra_metrics', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(), server_default='complete', nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feynman_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('concept', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rubric_json', sqlite.JSON(), nullable=True),
    sa.Column('model_explanation_text', sa.Text(), nullable=True),
    sa.Column('key_points_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feynman_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feynman_sessions_document_id'), ['document_id'], unique=False)

    op.create_table('feynman_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('gaps_identified', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feynman_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feynman_turns_session_id'), ['session_id'], unique=False)

    op.create_table('flashcards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('deck', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('is_user_edited', sa.Boolean(), nullable=False),
    sa.Column('fsrs_stability', sa.Float(), nullable=False),
    sa.Column('fsrs_difficulty', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('fsrs_state', sa.String(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('flashcard_type', sa.String(length=40), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=True),
    sa.Column('cloze_text', sa.Text(), nullable=True),
    sa.Column('source_content_hash', sa.String(length=16), nullable=True),
    sa.Column('note_id', sa.String(), nullable=True),
    sa.Column('chunk_classification', sa.String(length=20), nullable=True),
    sa.Column('section_heading', sa.String(length=300), nullable=True),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('concept_slug', sa.String(), nullable=True),
    sa.Column('source_scope', sa.String(), nullable=True),
    sa.Column('mapping_status', sa.String(), server_default=sa.text("'mapped'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index('idx_flashcards_concept_id', ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcards_concept_slug'), ['concept_slug'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('planned_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('golden_datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('generator_model', sa.String(), nullable=False),
    sa.Column('source_document_ids', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('golden_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golden_datasets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_golden_datasets_status'), ['status'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_hash', name='uq_image_doc_hash')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_document_id'), ['document_id'], unique=False)

    op.create_table('learning_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.String(length=16), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('target_unit', sa.String(length=16), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('deck_id', sa.String(), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_goals', schema=None) as batch_op:
        batch_op.create_index('idx_learning_goals_goal_type', ['goal_type'], unique=False)
        batch_op.create_index('idx_learning_goals_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_goals_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_goals_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_goals_goal_type'), ['goal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_goals_status'), ['status'], unique=False)

    op.create_table('learning_objectives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('covered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_objectives_document_id'), ['document_id'], unique=False)

    op.create_table('library_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('misconceptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('flashcard_id', sa.String(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('correction_note', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_tag_index',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('tag_full', sa.String(), nullable=False),
    sa.Column('tag_root', sa.String(), nullable=False),
    sa.Column('tag_parent', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('note_id', 'tag_full')
    )
    with op.batch_alter_table('note_tag_index', schema=None) as batch_op:
        batch_op.create_index('idx_note_tag_index_note_id', ['note_id'], unique=False)
        batch_op.create_index('idx_note_tag_index_tag_full', ['tag_full'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_auto_generated', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_key', sa.String(), nullable=False),
    sa.Column('payload_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_overrides_target_key'), ['target_key'], unique=False)

    op.create_table('pomodoro_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('focus_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('surface', sa.String(length=16), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('deck_id', sa.String(), nullable=True),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('pause_accumulated_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pomodoro_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pomodoro_sessions_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pomodoro_sessions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pomodoro_sessions_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pomodoro_sessions_status'), ['status'], unique=False)

    op.create_table('prediction_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('code_content', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('actual', sa.Text(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_events_document_id'), ['document_id'], unique=False)

    op.create_table('qa_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', sqlite.JSON(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_positions',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('last_section_id', sa.String(), nullable=True),
    sa.Column('last_section_heading', sa.String(length=300), nullable=True),
    sa.Column('last_pdf_page', sa.Integer(), nullable=True),
    sa.Column('last_epub_chapter_index', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('reading_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'section_id', name='uq_reading_progress_doc_section')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_document_id'), ['document_id'], unique=False)

    op.create_table('recommendation_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_ref', sa.String(), nullable=False),
    sa.Column('shown_count', sa.Integer(), nullable=False),
    sa.Column('last_shown_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'target_type', 'target_ref', name='uq_reco_kind_target')
    )
    op.create_table('review_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('flashcard_id', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('predicted_rating', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('section_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_summaries_document_id'), ['document_id'], unique=False)

    op.create_table('sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('heading', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('admonition_type', sa.String(length=20), nullable=True),
    sa.Column('parent_section_id', sa.String(), nullable=True),
    sa.Column('difficulty_estimate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('study_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_ref', sa.String(), nullable=True),
    sa.Column('transcript_path', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('cards_reviewed', sa.Integer(), nullable=False),
    sa.Column('cards_correct', sa.Integer(), nullable=False),
    sa.Column('accuracy_pct', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('planned_card_ids', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_streaks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_study_date', sa.Date(), nullable=True),
    sa.Column('streak_freezes_available', sa.Integer(), nullable=False),
    sa.Column('streak_freezes_used_this_week', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_aliases',
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('canonical_tag_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('alias')
    )
    with op.batch_alter_table('tag_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_aliases_canonical_tag_id'), ['canonical_tag_id'], unique=False)

    op.create_table('tag_merge_suggestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tag_a_id', sa.String(), nullable=False),
    sa.Column('tag_b_id', sa.String(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('suggested_canonical_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_merge_suggestions', schema=None) as batch_op:
        batch_op.create_index('idx_tag_merge_suggestions_status', ['status'], unique=False)

    op.create_table('teachback_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flashcard_id', sa.String(), nullable=False),
    sa.Column('user_explanation', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_points', sqlite.JSON(), nullable=False),
    sa.Column('missing_points', sqlite.JSON(), nullable=False),
    sa.Column('misconceptions', sqlite.JSON(), nullable=False),
    sa.Column('rubric_json', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_references',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('source_quality', sa.String(length=30), nullable=False),
    sa.Column('is_llm_suggested', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'section_id', 'term', 'url', name='uq_web_ref_doc_section_term_url')
    )
    with op.batch_alter_table('web_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_references_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_references_section_id'), ['section_id'], unique=False)

    op.create_table('xp_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xp_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_ledger_action'), ['action'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('golden_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ground_truth_answer', sa.Text(), nullable=False),
    sa.Column('context_hint', sa.Text(), nullable=False),
    sa.Column('source_chunk_id', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['golden_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('golden_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golden_questions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_golden_questions_source_document_id'), ['source_document_id'], unique=False)

    op.create_table('note_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_note_id', sa.String(), nullable=False),
    sa.Column('target_note_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_note_id', 'target_note_id', 'link_type', name='uq_note_link')
    )
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_links_source_note_id'), ['source_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_links_target_note_id'), ['target_note_id'], unique=False)

    op.create_table('note_sources',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'document_id')
    )
    # ### end Alembic commands ###

    # FTS5 virtual tables live outside Base.metadata, so autogenerate never emits
    # them. Reuse db_init's DDL rather than restating it -- two copies would drift,
    # and column order is load-bearing (I-4).
    for fts_ddl in ALL_FTS5_DDL:
        op.execute(fts_ddl)


def downgrade() -> None:
    """Downgrade schema."""
    for fts_table in _FTS_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {fts_table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_sources')
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_links_target_note_id'))
        batch_op.drop_index(batch_op.f('ix_note_links_source_note_id'))

    op.drop_table('note_links')
    with op.batch_alter_table('golden_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golden_questions_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_golden_questions_dataset_id'))

    op.drop_table('golden_questions')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('xp_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_ledger_action'))

    op.drop_table('xp_ledger')
    with op.batch_alter_table('web_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_references_section_id'))
        batch_op.drop_index(batch_op.f('ix_web_references_document_id'))

    op.drop_table('web_references')
    op.drop_table('teachback_results')
    with op.batch_alter_table('tag_merge_suggestions', schema=None) as batch_op:
        batch_op.drop_index('idx_tag_merge_suggestions_status')

    op.drop_table('tag_merge_suggestions')
    with op.batch_alter_table('tag_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_aliases_canonical_tag_id'))

    op.drop_table('tag_aliases')
    op.drop_table('summaries')
    op.drop_table('study_streaks')
    op.drop_table('study_sessions')
    op.drop_table('study_events')
    op.drop_table('settings')
    op.drop_table('sections')
    with op.batch_alter_table('section_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_summaries_document_id'))

    op.drop_table('section_summaries')
    op.drop_table('review_events')
    op.drop_table('recommendation_feedback')
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_document_id'))

    op.drop_table('reading_progress')
    op.drop_table('reading_positions')
    op.drop_table('qa_history')
    with op.batch_alter_table('prediction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_events_document_id'))

    op.drop_table('prediction_events')
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pomodoro_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_pomodoro_sessions_goal_id'))
        batch_op.drop_index(batch_op.f('ix_pomodoro_sessions_document_id'))
        batch_op.drop_index(batch_op.f('ix_pomodoro_sessions_deck_id'))
        batch_op.drop_index(batch_op.f('ix_pomodoro_sessions_created_at'))

    op.drop_table('pomodoro_sessions')
    with op.batch_alter_table('overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overrides_target_key'))

    op.drop_table('overrides')
    op.drop_table('notes')
    with op.batch_alter_table('note_tag_index', schema=None) as batch_op:
        batch_op.drop_index('idx_note_tag_index_tag_full')
        batch_op.drop_index('idx_note_tag_index_note_id')

    op.drop_table('note_tag_index')
    op.drop_table('misconceptions')
    op.drop_table('library_summaries')
    with op.batch_alter_table('learning_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_objectives_document_id'))

    op.drop_table('learning_objectives')
    with op.batch_alter_table('learning_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_goals_status'))
        batch_op.drop_index(batch_op.f('ix_learning_goals_goal_type'))
        batch_op.drop_index(batch_op.f('ix_learning_goals_document_id'))
        batch_op.drop_index(batch_op.f('ix_learning_goals_deck_id'))
        batch_op.drop_index('idx_learning_goals_status')
        batch_op.drop_index('idx_learning_goals_goal_type')

    op.drop_table('learning_goals')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_document_id'))

    op.drop_table('images')
    with op.batch_alter_table('golden_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golden_datasets_status'))
        batch_op.drop_index(batch_op.f('ix_golden_datasets_created_at'))

    op.drop_table('golden_datasets')
    op.drop_table('focus_sessions')
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_concept_slug'))
        batch_op.drop_index(batch_op.f('ix_flashcards_concept_id'))
        batch_op.drop_index('idx_flashcards_concept_id')

    op.drop_table('flashcards')
    with op.batch_alter_table('feynman_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feynman_turns_session_id'))

    op.drop_table('feynman_turns')
    with op.batch_alter_table('feynman_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feynman_sessions_document_id'))

    op.drop_table('feynman_sessions')
    op.drop_table('eval_runs')
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_document_id'))

    op.drop_table('enrichment_jobs')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))

    op.drop_table('documents')
    op.drop_table('document_tag_provenance')
    with op.batch_alter_table('document_tag_index', schema=None) as batch_op:
        batch_op.drop_index('idx_document_tag_index_tag_full')
        batch_op.drop_index('idx_document_tag_index_document_id')

    op.drop_table('document_tag_index')
    with op.batch_alter_table('content_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_activity_last_meaningful_at'))

    op.drop_table('content_activity')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_status'))
        batch_op.drop_index(batch_op.f('ix_concepts_slug'))
        batch_op.drop_index(batch_op.f('ix_concepts_parent_id'))
        batch_op.drop_index('idx_concepts_parent_id')

    op.drop_table('concepts')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_auto_document_id'))
        batch_op.drop_index('idx_collections_auto_doc_id')

    op.drop_table('collections')
    with op.batch_alter_table('collection_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_members_member_id'))
        batch_op.drop_index(batch_op.f('ix_collection_members_collection_id'))

    op.drop_table('collection_members')
    with op.batch_alter_table('code_snippets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_snippets_document_id'))

    op.drop_table('code_snippets')
    op.drop_table('cluster_suggestions')
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_document_id'))

    op.drop_table('clips')
    op.drop_table('chunks')
    with op.batch_alter_table('chat_suggestion_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_suggestion_history_document_id'))

    op.drop_table('chat_suggestion_history')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_created_at'))

    op.drop_table('chat_sessions')
    op.drop_table('canonical_tags')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_document_id'))

    op.drop_table('annotations')
    op.drop_table('achievements')
    # ### end Alembic commands ###
